#!/usr/bin/env python3
# SPDX-FileCopyrightText: APM contributors
# SPDX-License-Identifier: Apache-2.0

"""Generate APM v2's experimental/unverified model-only Spectre layer."""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python 3.9/3.10
    import tomli as tomllib

ROOT = Path(__file__).resolve().parents[1]
VARIATION_TARGET = ROOT / "variation/spectre/benchmark_variation.scs"
PASSIVE_TARGET = ROOT / "passives/spectre/benchmark_passives.scs"
CMG_SOURCE = ROOT / "models/apm016f/ngspice/apm016f_multivt_models.inc"
CMG_TARGET = ROOT / "models/apm016f/spectre/apm016f_multivt.scs"
SPDX_COPYRIGHT = "SP" + "DX-FileCopyrightText: APM contributors"
SPDX_LICENSE = "SP" + "DX-License-Identifier: Apache-2.0"


def _load(path: Path) -> dict[str, Any]:
    with path.open("rb") as handle:
        return tomllib.load(handle)


def _number(value: Any) -> str:
    return f"{float(value):.17g}"


def _relative_include(target: Path, source: Path) -> str:
    return os.path.relpath(source, target.parent).replace(os.sep, "/")


def _inverse_expression(
    intent: str,
    linear: float,
    quadratic: float,
    nominal: float,
    coefficient_prefix: str,
) -> str:
    coefficient_a = f"{coefficient_prefix}_a"
    coefficient_b = f"{coefficient_prefix}_b"
    if quadratic == 0.0:
        delta = f"{intent}/{coefficient_a}"
    else:
        sign = "+" if linear > 0.0 else "-"
        delta = (
            f"2*{intent}/({coefficient_a}{sign}sqrt({coefficient_a}*{coefficient_a}+"
            f"4*{coefficient_b}*{intent}))"
        )
    if nominal == 0.0:
        return delta
    return f"{_number(nominal)}+{delta}"


def _family_records() -> list[tuple[Path, dict[str, Any], Path, dict[str, Any]]]:
    records = []
    for manifest_path in sorted(ROOT.glob("models/*/families/*/family.toml")):
        manifest = _load(manifest_path)
        spectre_paths = [
            ROOT / item for item in manifest["backend_bindings"] if "/spectre/" in item
        ]
        if len(spectre_paths) != 1:
            raise RuntimeError(
                f"{manifest_path.relative_to(ROOT)} must bind exactly one Spectre artifact"
            )
        binding_path = spectre_paths[0]
        records.append((manifest_path, manifest, binding_path, _load(binding_path)))
    if len(records) != 13:
        raise RuntimeError(f"expected 13 Spectre family bindings, found {len(records)}")
    return records


def _render_family(
    manifest: dict[str, Any],
    binding: dict[str, Any],
    adapter: dict[str, Any],
    benchmark: dict[str, Any],
) -> str:
    technology = manifest["technology_id"]
    family = manifest["id"]
    target = ROOT / binding["wrapper"]
    lines = [
        f"// {SPDX_COPYRIGHT}",
        f"// {SPDX_LICENSE}",
        "//",
        f"// APM v2 model-only Spectre binding for {technology}/{family}",
        "// EXPERIMENTAL / UNVERIFIED",
        "// Generated by tools/generate_spectre_v2.py.",
        "// Static structure only: not parsed or simulated by Cadence Spectre.",
        "// Include variation/spectre/benchmark_variation.scs with one section.",
        "",
    ]
    include_language = binding["include_language"]
    if include_language == "spice":
        lines.append("simulator lang=spice")
        lines.extend(
            f'.include "{_relative_include(target, ROOT / source)}"'
            for source in binding["model_includes"]
        )
        lines.extend(["simulator lang=spectre", ""])
    elif include_language == "spectre":
        lines.extend(["simulator lang=spectre"])
        lines.extend(
            f'include "{_relative_include(target, ROOT / source)}"'
            for source in binding["model_includes"]
        )
        lines.append("")
    else:
        raise RuntimeError(f"unsupported include language {include_language!r}")

    devices = {item["id"]: item for item in manifest["device"]}
    for device_id, device in devices.items():
        device_adapter = adapter["device"][device_id]
        public_parameters = device["parameters"]
        defaults = {
            "w": device.get("default_w_m"),
            "l": device["lmin_m"],
            "nfin": 1,
        }
        parameter_text = " ".join(
            f"{name}={_number(defaults[name]) if name != 'nfin' else defaults[name]}"
            for name in public_parameters
        )
        if manifest["architecture"] == "planar_bulk":
            match_size = (
                f"(w*l)/({_number(device_adapter['reference_w_m'])}*"
                f"{_number(device_adapter['reference_l_m'])})"
            )
        else:
            match_size = (
                f"(nfin*l)/({int(device_adapter['reference_nfin'])}*"
                f"{_number(device_adapter['reference_l_m'])})"
            )
        polarity = device["polarity"]
        global_prefix = f"apm_bench_{technology}_{polarity}"
        vth_a = float(device_adapter["vth_fit_linear"])
        vth_b = float(device_adapter["vth_fit_quadratic"])
        drive_a = float(device_adapter["drive_fit_linear"])
        drive_b = float(device_adapter["drive_fit_quadratic"])
        vth_intent = (
            f"{_number(benchmark['mos']['global']['vth_shift_sigma'])}*"
            f"{global_prefix}_vth_global_z+"
            f"{_number(benchmark['mos']['local']['vth_shift_sigma_ref'])}*"
            "apm__mos_vth_local_z/sqrt(apm__match_size)"
        )
        drive_intent = (
            f"(1+{_number(benchmark['mos']['global']['drive_shift_sigma'])}*"
            f"{global_prefix}_drive_global_z)*(1+"
            f"{_number(benchmark['mos']['local']['drive_shift_sigma_ref'])}*"
            "apm__mos_drive_local_z/sqrt(apm__match_size))-1"
        )
        native = binding["device"][device_id]
        fixed = native.get("fixed_parameters", "")
        raw_parameters = (
            f"{adapter['vth_raw_parameter']}=apm__vth_raw "
            f"{adapter['drive_raw_parameter']}=apm__drive_raw"
        )
        core_suffix = " ".join(item for item in (f"{name}={name}" for name in public_parameters))
        if fixed:
            core_suffix += f" {fixed}"
        core_suffix += f" {raw_parameters}"
        lines.extend(
            [
                f"subckt {device['public_name']} (d g s b)",
                f"parameters {parameter_text}",
                f"parameters apm__match_size={match_size}",
                (
                    f"parameters apm__vth_adapter_a={_number(vth_a)} "
                    f"apm__vth_adapter_b={_number(vth_b)}"
                ),
                (
                    f"parameters apm__drive_adapter_a={_number(drive_a)} "
                    f"apm__drive_adapter_b={_number(drive_b)}"
                ),
                f"parameters apm__vth_intent={vth_intent}",
                f"parameters apm__drive_intent={drive_intent}",
                "parameters apm__vth_raw="
                + _inverse_expression(
                    "apm__vth_intent",
                    vth_a,
                    vth_b,
                    0.0,
                    "apm__vth_adapter",
                ),
                "parameters apm__drive_raw="
                + _inverse_expression(
                    "apm__drive_intent",
                    drive_a,
                    drive_b,
                    float(adapter["drive_raw_nominal"]),
                    "apm__drive_adapter",
                ),
                (
                    f"{binding['instance_prefix']}apm__core (d g s b) "
                    f"{native['native_model']} {core_suffix}"
                ),
                f"ends {device['public_name']}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def _global_names(technologies: list[str]) -> list[str]:
    return [
        f"apm_bench_{technology}_{polarity}_{intent}_global_z"
        for technology in technologies
        for polarity in ("n", "p")
        for intent in ("vth", "drive")
    ] + ["apm_bench_r_global_z", "apm_bench_c_global_z"]


def _render_variation(benchmark: dict[str, Any], technologies: list[str]) -> str:
    globals_ = _global_names(technologies)
    locals_ = [
        "apm__mos_vth_local_z",
        "apm__mos_drive_local_z",
        "apm__r_local_z",
        "apm__c_local_z",
    ]
    lines = [
        f"// {SPDX_COPYRIGHT}",
        f"// {SPDX_LICENSE}",
        "// APM v2 model-only Spectre benchmark variation",
        "// EXPERIMENTAL / UNVERIFIED",
        "// Not parsed or simulated by Cadence Spectre.",
        "// Benchmark Global = Spectre montecarlo variations=process.",
        "// Benchmark Local = Spectre montecarlo variations=mismatch.",
        "// Benchmark All = Spectre montecarlo variations=all.",
        "// Spectre owns its random samples; seed identity with ngspice is not required.",
        "",
        "simulator lang=spectre",
        "",
        "library apm_benchmark_variation_v2",
        "",
        "section bench_mc",
        *[f"parameters {name}=0" for name in [*globals_, *locals_]],
        "",
        "statistics {",
        "  process {",
        *[f"    vary {name} dist=gauss std=1 percent=no" for name in globals_],
        "  }",
        "  mismatch {",
        *[f"    vary {name} dist=gauss std=1 percent=no" for name in locals_],
        "  }",
        "}",
        "endsection bench_mc",
        "",
    ]
    corner_key = {
        "vth": {"n": "vth_n_sigma", "p": "vth_p_sigma"},
        "drive": {"n": "drive_n_sigma", "p": "drive_p_sigma"},
    }
    for corner in ("bench_tt", "bench_ff", "bench_ss", "bench_fs", "bench_sf"):
        values = benchmark["corner"][corner]
        lines.extend([f"section {corner}"])
        for technology in technologies:
            for polarity in ("n", "p"):
                for intent in ("vth", "drive"):
                    name = f"apm_bench_{technology}_{polarity}_{intent}_global_z"
                    lines.append(
                        f"parameters {name}={_number(values[corner_key[intent][polarity]])}"
                    )
        lines.extend(
            [
                f"parameters apm_bench_r_global_z={_number(values['resistor_scale_sigma'])}",
                f"parameters apm_bench_c_global_z={_number(values['capacitor_scale_sigma'])}",
                *[f"parameters {name}=0" for name in locals_],
                f"endsection {corner}",
                "",
            ]
        )
    lines.append("endlibrary apm_benchmark_variation_v2")
    return "\n".join(lines) + "\n"


def _render_passives(passives: dict[str, Any]) -> str:
    return f"""// {SPDX_COPYRIGHT}
// {SPDX_LICENSE}
// APM v2 model-only Spectre benchmark passives
// EXPERIMENTAL / UNVERIFIED
// Not parsed or simulated by Cadence Spectre.

simulator lang=spectre

subckt Rbench (p n)
parameters value=1k tc1=0 match_size=1
parameters apm__r_scale=(1+{_number(passives["resistor"]["global_sigma"])}*apm_bench_r_global_z)*(1+{_number(passives["resistor"]["local_sigma_ref"])}*apm__r_local_z/sqrt(match_size))
Rapm__core (p n) resistor r=value*apm__r_scale tc1=tc1 tnom=27
ends Rbench

subckt Cbench (p n)
parameters value=1p tc1=0 match_size=1
parameters apm__c_scale=(1+{_number(passives["capacitor"]["global_sigma"])}*apm_bench_c_global_z)*(1+{_number(passives["capacitor"]["local_sigma_ref"])}*apm__c_local_z/sqrt(match_size))
Capm__core (p n) capacitor c=value*apm__c_scale tc1=tc1 tnom=27
ends Cbench
"""


def _render_cmg() -> str:
    text = CMG_SOURCE.read_text(encoding="utf-8")
    blocks = re.findall(
        r"(?ms)^\.model\s+(\w+)\s+bsimcmg_va\s+type=([-+]?1)(?P<body>.*?)"
        r"(?=^\.model|\Z)",
        text,
    )
    if len(blocks) != 6:
        raise RuntimeError(f"expected six APM016F BSIM-CMG models, found {len(blocks)}")
    lines = [
        f"// {SPDX_COPYRIGHT}",
        f"// {SPDX_LICENSE}",
        "// APM-authored APM016F multi-Vt Spectre-native transcription",
        "// EXPERIMENTAL / UNVERIFIED",
        "// Generated mechanically from apm016f_multivt_models.inc; only the",
        "// compact-model language/name and type spelling are translated.",
        "simulator lang=spectre",
        "",
    ]
    for name, type_value, body in blocks:
        parameters = " ".join(
            line.strip().lstrip("+").strip() for line in body.splitlines() if line.strip()
        )
        polarity = "n" if type_value == "1" else "p"
        lines.extend([f"model {name} bsimcmg type={polarity} {parameters}", ""])
    return "\n".join(lines).rstrip() + "\n"


def render_all() -> dict[Path, str]:
    benchmark = _load(ROOT / "variation/benchmark_v2.toml")
    adapters = _load(ROOT / "variation/adapters_v2.toml")
    passives = _load(ROOT / "passives/benchmark_v2.toml")
    records = _family_records()
    outputs: dict[Path, str] = {
        CMG_TARGET: _render_cmg(),
        VARIATION_TARGET: _render_variation(
            benchmark, sorted({record[1]["technology_id"] for record in records})
        ),
        PASSIVE_TARGET: _render_passives(passives),
    }
    for _manifest_path, manifest, _binding_path, binding in records:
        selector = f"{manifest['technology_id']}/{manifest['id']}"
        outputs[ROOT / binding["wrapper"]] = _render_family(
            manifest, binding, adapters["family"][selector], benchmark
        )
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = False
    for path, expected in render_all().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
                stale = True
            else:
                print(f"up to date: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    return int(stale)


if __name__ == "__main__":
    raise SystemExit(main())
